# Generated by Django 5.2 on 2026-02-05 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='質問タイトル')),
                ('detail', models.TextField(max_length=4000, verbose_name='質問本文')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='画像URL')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('status', models.CharField(choices=[('1', '解決済み'), ('2', '未解決')], default='2', max_length=16, verbose_name='ステータス')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgeapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgeapp.question', verbose_name='質問')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField(max_length=4000, verbose_name='回答本文')),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgeapp.question', verbose_name='質問')),
            ],
        ),
    ]
