# Generated by Django 5.2 on 2026-02-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
    ]
