# Generated by Django 5.2 on 2026-02-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeapp', '0002_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledgeapp.question', verbose_name='質問'),
        ),
    ]
